preprocessing:
  resize_dims: [640, 640]
  clahe:
    clip_limit: 2.0
    tile_grid_size: [8, 8]
  gaussian_blur:
    kernel_size: [3, 3]
    sigma: 1.0
  unsharp_masking:
    kernel_size: [5, 5]
    sigma: 1.0
    amount: 1.5
  bilateral:
    diameter: 9
    sigma_color: 50
    sigma_space: 50
  illumination:
    dark_threshold: 100
    bright_threshold: 200
    adaptation_factor: 1.5

inference:
  conf_threshold: 0.35
  iou_threshold: 0.45
  model_size: "medium"  # nano, small, medium, large, xlarge
  device: "cuda"  # cuda or cpu
  batch_size: 2
  fp16: true  # Enable half-precision inference
  fuse: true  # Fuse layers for optimal performance
  warmup_iterations: 10  # Warm up GPU
  max_batch_size: 4
  dynamic_batch_size: true

system:
  cuda_memory_fraction: 0.9  # Limit CUDA memory usage
  num_workers: 4  # Number of worker threads
  pin_memory: true  # Pin CPU memory for faster GPU transfer

visualization:
  window_name: "Crack Detection"
  font_scale: 0.5
  thickness: 2
